### ISSUE TITLE
Glowing extension icon: signal site safety level to users

### ISSUE THREAD

**Issue by danielgoldelman** [privacy-tech-lab/privacy-pioneer#288]
While we test our extension and build our analysis in the next stage of this project, it may be a cool idea to think about including recommendations to users about inputting data on the sites they are visiting. For example, if a site is sharing a lot of data, we may recommend that a user not put personal data into any forms. We could put green, yellow, or red dots in the popup with a tooltip that could explain why we would or would not trust this site with your data.

For users that are not well versed in the concepts used in this extension, this would be a very helpful feature, as it would justify putting time into learning more about the invasive procedures of the internet.

**Comment by SebastianZimmeck** [comment]
We discussed today that @danielgoldelman will take the lead on this.

**Comment by danielgoldelman** [comment]
^ Changes made so that the icon changes when above a certain threshold. Currently it just changes to the box with a question mark that was our previous logo:
<img width="131" alt="Screen Shot 2021-09-06 at 9 38 39 AM" src="https://user-images.githubusercontent.com/64672619/132225867-9024769e-eedf-43f9-b001-755f68b291f6.png">
Updates we need to discuss: 
- What do we want for the replacement favicon?
- What is our threshold going to be?
- What is an adequate wait time for the initial dump of requests?

**Comment by SebastianZimmeck** [comment]
> What do we want for the replacement favicon?

We could just have the background change colors like in OptMeowt. Though, rather than green, a light orange or some similar color may be better to signal that there is a problem. 

Normal favicon: 
<img width="34" alt="Screen Shot 2021-09-06 at 9 26 55 AM" src="https://user-images.githubusercontent.com/11034003/132244717-32d6cc67-a967-4ef1-aca5-6ec51fa17ff8.png">

Favicon in case of exceeding threshold: 
<img width="33" alt="Screen Shot 2021-09-06 at 9 27 26 AM" src="https://user-images.githubusercontent.com/11034003/132244764-6f232b38-1602-4db0-9701-279e5193bfe9.png">

> What is our threshold going to be?

For the time being, let's pick something that seems reasonable; something that would have about a third of sites in the highlighted category. Setting the threshold and how exactly to do it we can address later. We would need to look more into it. Could you open an issue on that, @danielgoldelman?)  

> What is an adequate wait time for the initial dump of requests?

What is the wait time? The time for determining whether the threshold is exceeded, after which the changed favicon is displayed, ...?

**Comment by danielgoldelman** [comment]
@SebastianZimmeck When a website is first loading, there is a large amount of requests that appear very quickly, which tapers off quite fast. Since we don't want extra analysis per request, my thought was to change the favicon after checking if that initial dump of requests created enough evidence to go above our threshold. Thus the wait time is there so that we wait until the initial dump terminates, then change the favicon accordingly.

**Comment by SebastianZimmeck** [comment]
Yes, that is a good idea! Let's do it that way.

**Comment by danielgoldelman** [comment]
^ moved constants to constants.js, small change to make sure that we are displaying the correct favicon. There are a few examples where changing the page can keep the incorrect favicon, but this change fixes that problem.

I believe that 5 seconds is a good cutoff. By simple calculation using a limited number of sites, >90% of requests we generated evidence for occurred within the first 5 seconds after loading a site. I believe we should wait for full testing to determine the correct threshold.

Next step is to get the new favicon for large evidence.

**Comment by SebastianZimmeck** [comment]
> Next step is to get the new favicon for large evidence.

Large evidence is evidence surpassing the threshold, or what is it?

**Comment by SebastianZimmeck** [comment]
Great, @danielgoldelman! Is the rocket also now uniform across the favicons and other assets?

**Comment by danielgoldelman** [comment]
@SebastianZimmeck, @Lr-Brown and I tried out multiple variations of our favicon recently, and the more stylized rocket was too small to really be able to seen easily when in dark mode (we tried multiple color variations). I am now thinking that keeping the original favicon, then just changing the color of the rocket, is a better approach. We should discuss/view the current change today.

**Comment by SebastianZimmeck** [comment]
Sounds good, @danielgoldelman!

**Comment by SebastianZimmeck** [comment]
@notowen333 will provide the final touches.
