### ISSUE TITLE
Is disconnectFingerprintSearch Redundant?

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#298]
Right now, we take the [Firefox URL Classification](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onHeadersReceived) for all disconnect categories but do our own iteration for "fingerprinting invasive" category. It seems to me that this is redundant and the "fingerprinting" flag from the URL classification would come up if an element of this list was present. @danielgoldelman Am I missing something here?

**Comment by notowen333** [comment]
@danielgoldelman Okay, I see. That being said, maybe it still makes sense to kill the functionality:

- I haven't seen this function yield a label.
- It will be easier to explain our analysis if we just align ourselves with Firefox in terms of the Disconnect list.

**Comment by danielgoldelman** [comment]
Ok, after a little more investigation, I'm ok with removing disconnectFingerprintSearch, meaning that we don't really need ```services.json``` (disconnect's list) anymore since we will be going with urlClassification, but I think we should keep it in the codebase so that if Google implements the StreamFilter API in Chrome we can use the list (since they will probably not have a urlClassification property).

**Comment by SebastianZimmeck** [comment]
> we should keep it in the codebase so that if Google implements the StreamFilter API

OK, one way to do this is to tag the current codebase with the functionality included, comment here (and/or wherever else someone might look for this), and remove the functionality. That way we could go back to the tagged version of the code.

**Comment by notowen333** [comment]
I removed the functionality in the above commit. The PR will be linked too. Since this whole issue is dedicated to this, I think it will be easy to find if we need it.
