### ISSUE TITLE
Implement Privacy Pioneer for Chrome

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#322]
Today @notowen333 brought up the very good point that we actually may not lose that much functionality in a Chrome implementation and might as well do it. Essentially, only the [webRequest.filterResponseData()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData) API would be missing in Chrome. However, we could get request header and body data. 

The implementation could be also fairly straightforward with two techniques coming to mind that could be applied individually or combined. First, we could have a built script with different builds for Chrome and Firefox. Second, we could use conditionals in the codebase to say "if Firefox, then run this code; if Chrome, run that code."

It probably makes sense to finalize the Firefox implementation first, and then attend to the modifications to make it work in Chrome.

**Comment by SebastianZimmeck** [comment]
@danielgoldelman is on the lead here.

**Comment by danielgoldelman** [comment]
After initial testing, the modifications needed to make Privacy Pioneer on Chromium seems very straightforward, but will consume significant time when we are ready to actually port the extension. A few main observations are:
- For *most* browser apis, we can just rename them ```chrome```. Ex ```browser.webRequest.onBeforeRequest``` becomes ```chrome.webRequest.onBeforeRequest```. This changes nothing in Firefox, and allows the extension to run on chrome.
  - If on firefox, ```browser.tabs``` is utilized. If on chrome, ```chrome.tabs``` is utilized
  - the ```tabs``` api runs a bit differently in chrome. The callback is passed as the second input, and as such does not use the ```.then``` syntax
- The request information we utilize in Firefox is obviously different in chrome, so quite a few changes are needed in that aspect of the code. Ex: the rootUrl from details in analyze.js is ```details.originUrl``` in firefox and ```details.url``` in chrome
- ```export const isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);``` is a quick and easy way to see if the extension is operating in chrome.
- The code needed to do the if firefox/if chrome method is very simple but could clutter the extension's code. I agree with the sentiment that finalizing the Firefox extension and then making the chrome port is the best course of action, even though we could certainly take the time to do it now.

**Comment by danielgoldelman** [comment]
### Changes to be made:

Notes:
- We will need to change how we create and analyze the snippets since we no longer have response data
- Other apis may be differently implimented (similar to the changes needed for tabs)
- Line numbers not given below since we don't know how the code will change. Changes are listed in the order they appeared in main when the list was created.

document | before | after
--- | --- | ---
background.js | browser.runtime.onMessage.addListener((request, sender, sendResponse) => {  | chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
|  | browser.tabs.query(...).then() as normal | chrome.tabs.query(..., callback fn)
|  | browser.runtime.onMessage.addListener( | chrome.runtime.onMessage.addListener(
|  | browser.webRequest.onBeforeRequest.addListener( | chrome.webRequest.onBeforeRequest.addListener(
|  | browser.downloads.onChanged.addListener(async function (downloadDelta) { | chrome.downloads.onChanged.addListener(async function (downloadDelta) {
analyze.js | browser.tabs.get(details.tabId) | chrome ? : chrome.tabs.get(details.tabId) : browser.tabs.get(details.tabId)
|  | another as above |
|  | request.rootUrl = details.originUrl | isChrome ? request.rootUrl = details.url: request.rootUrl = details.originUrl
|  | filterResponseData api | set request.responseData = '', then call resolveBuffer
| scanHTTP.js | urlSearch with urlClassification | urlSearch with disconnect list
| notifications.js | browser.tabs.onActivated.addListener((activeInfo) => { | if chrome: <br> chrome.tabs.onActivated.addListener(chrome.tabs.query({...}, callback fn)) <br> else: browser.tabs... as normal
| initiateDownload.js | browser.downloads.download ({ | chrome.downloads.download ({
| libs/settings/index.js | browser.runtime.sendMessage({ ... }) | chrome.runtime.sendMessage({ ... })
|  | same as above | 
| src/options/views/index.js | browser.runtime.sendMessage({ | chrome.runtime.sendMessage({
| src/popup/views/website-view/index.js | const url = browser.runtime.getURL("options.html") | const url = chrome.runtime.getURL("options.html")
|  | browser.tabs.query({ url: url }, function (tabs) { | if chrome: <br> change all browser. to chrome. <br> else: same as before
|  | browser.runtime.onMessage.addListener(message) <br>browser.runtime.sendMessage({ msg: "background.currentTab" }) <br> return () => {browser.runtime.onMessage.removeListener(message)} | chrome.runtime.onMessage.addListener(message)<br> chrome.runtime.sendMessage({ msg: "background.currentTab" }) <br> return () => {chrome.runtime.onMessage.removeListener(message)}

**Comment by SebastianZimmeck** [comment]
Excellent overview, @danielgoldelman!

**Comment by SebastianZimmeck** [comment]
Most of the changes may be straightforward. Maybe, a week's work. We should finish Firefox first, and then move to Chrome.

**Comment by SebastianZimmeck** [comment]
As we discussed today, we will decide this question next week after having addressed the remaining outstanding implementation issues.

**Comment by danielgoldelman** [comment]
^ Initial changes implemented to allow PrivacyPioneer to work on Chrome. Entire frontend seems to be working, but backend reworks are needed. Next steps: change the backend to use the right jargon/identifiers for chrome apis, then run tests to make sure chrome and firefox work similarly (considering Chrome does not give us response data).

**Comment by SebastianZimmeck** [comment]
> Entire frontend seems to be working

Excellent!

**Comment by SebastianZimmeck** [comment]
One very important point, current Chrome extensions with Manifest V2 will [stop running](https://developer.chrome.com/blog/mv2-transition/) on Chromium in January 2023. So, we might as well implement for Manifest V3 right away. Could you look into that, @danielgoldelman ?

**Comment by danielgoldelman** [comment]
We determined that since the ```filterResponseData``` API is not in Chrome, and since ```responseData``` yields an overwhelming amount of the data we display to the user in the Firefox implementation, a Chrome port is not worth pursuing at this time. We will leave this issue open to return to once or if Google adds the ```filterResponseData``` API.

**Comment by SebastianZimmeck** [comment]
As @danielgoldelman is saying: 

1. There is no technical obstacle for a Chrome port. In fact, it is actually fairly easy and @danielgoldelman has done it. Privacy Pioneer runs fine on Chrome.
2. But because Chrome does not support the response API, a large part of the web traffic cannot be analyzed. The analysis results for Chrome are just very slim.
