### ISSUE TITLE
Generalize Structured Location Routines

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#358]
## Overview
Right now, the location routines have two issues:
1. They are US-centric
2. We aren't generalizing the creation of regular expressions for all data fields

### Internationalizing Location

The easy nomenclature change is that everywhere that says "State" should instead say "Region". The functionality change is that we have input validation routines and regular expression routines which are specifically scoped to US data. We want to generalize all of these routines.

### Regular expression creation

This one is simple and similar to #357. Right now, we turn "New Jersey" into `/New.?Jersey/i,` through a hard-coded case statement in `structuredRoutines.js`. 
- First, we want to replace this with a function that generalizes that. 
- Second, we want to use the same generalized function for "City" and "Street Address" as well.

Here is a code snippet that I used to roughly achieve this function when gathering data for ML:

```
function toRegex(str) {

    str = str.replace(/\s/g, '\\D?') // \s is space character or equiv
    str = str.replace(/\./g, '\\D?') // \. is "." character
    str = str.replace(/-/g, '\\D?') // also replace dashes with optional non digits (mostly for INTL)
    return new RegExp(str, "i")
 }
```

### Hard Part: Zip Codes

International zip codes are all over the place. Some areas have no zip codes and others have zip codes in very different formats than the US. For US zip codes, we add non-digits to both ends of the regular expression we create. We need to explore if this is internationally generalizable, and, if not, come up with a way to handle different formats.

One idea could be:

1. check if the zip is all numbers
2. if yes, do what we do now and add nondigits to either end of the regular expression
3. if no, do an alternate routine that we come up with for differently structured zips.

## Motivation

Given that we are training our ML on international data, we want our extension to be compatible with international location data. On a different note, we make our tool more accessible to millions of potential users by creating internationally generalized location routines.

**Comment by SebastianZimmeck** [comment]
Out of the issues @notowen333 recently created (#355, #356, #357 and this one), this one seems to be the most important to me. I would say more generally, we have to fit our analysis, UI, and other implementation to our ML data (which is not set in stone at the moment). So, I would seed this issue beyond our location category but more generally "fit our implementation to the data types we have and make any modification necessary for that."

**Comment by JustinCasler** [comment]
As mentioned in the issue, the generalizing to international location has already been achieved in the crawl, and this would likely be easy to transfer over.

After doing some research on international zip codes, there is no set pattern. Looking at the crawl's VPN data, I've been able to create some rough categories.

- Standard all numbers (1234, 12345, or 123456)

- Space or dash (123 45, 1234-567, 123-4567 etc.)

- Letters (A1, V3B 1D1, LV-1001)

Although imperfect, I think regex creation can become somewhat generalized using a similar, more nuanced thought process to what was laid out above. Namely:

- check if the zip is all numbers

- if yes, do what we do now and add non digits to either end of the regular expression

- if no, check for spaces/dashes and letters. Based on findings (spaces + letters, only spaces, only letters), do one of the few alternate routines that we come up with for differently structured zips.

I will attempt to implement this thought process for the new crawl, and once successful, it should be easily transferable like the intentional locations.

**Comment by SebastianZimmeck** [comment]
OK, thanks, @JustinCasler! Maybe, we can add some prominent cases that we encounter using our VPN, e.g., UK zip codes as they seem to be in recognizable format. We do not need to be comprehensive. We may get lost in details otherwise. The point for us is more to show how it can be done in principle (and if someone would put in the work, they could do this comprehensively).
