### ISSUE TITLE
Implement Automated QA testing with Jest

### ISSUE THREAD

**Issue by lr-brown** [privacy-tech-lab/privacy-pioneer#403]
As discussed, we want to discover whether automated testing is a sustainable way to Quality check our extension.

**Comment by SebastianZimmeck** [comment]
Great, thanks, @lr-brown! It would be good, @jjeancharles, if you can get involved as well.

**Comment by lr-brown** [comment]
I think the best way to approach this is by organizing the tests by each screen. Each view in the 'views' directory will have its own  __tests__ directory that will have a collection of test files that relate to that view. For example, the 'watchlist-view' directory will have test files relating to adding items to the watchlist and accessing watchlist items from the indexed-DB.

**Comment by SebastianZimmeck** [comment]
I'd prefer if we had one central test folder. Otherwise, in my mind, it is hard to keep track of tests if they scattered through the codebase. Even if we have them in a central location, they can still be organized in the same directory structure as the code requires, if that helps.

(cc'ing @sophieeng as she is working on testing for OptMeowt)

**Comment by lr-brown** [comment]
Judeley and I will be splitting the testing up here's what we'll each be working on: 

### Judeley:

- [ ] Watchlist View

- [ ] Setting View 

### Logan:

- [ ] Search View

- [ ] Home View

- [ ] Popup

**Comment by lr-brown** [comment]
Add status badges to the ReadMe
