### ISSUE TITLE
Check that Watchlist notifications are working and fix as necessary

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#441]
I did not get a notification for the following situation.

<img width="898" alt="Screenshot 2022-12-23 at 10 36 30 PM" src="https://user-images.githubusercontent.com/11034003/209407577-0d3fc57f-38f7-4f16-b09e-d8f6cb6f5e9b.png">

I enabled notifications for PP in Firefox, turned on notifications for IP addresses, went to a few "what's my IP sites", but did not receive any notifications. The IP address from the IP sites was exactly the one shown in the Watchlist.

Does the notification functionality work?

If not, we need to fix it.

**Comment by danielgoldelman** [comment]
After investigation, notifications do work ONLY for user-entered watchlist entries. The computer-generated entries are not working. This is very likely due to the probability that they are generated BEFORE the user accepts notifications in the extension based on some new changes. I will investigate and correct this.

**Comment by lr-brown** [comment]
After more investigation, this is not a bug but an intentional decision made to categorize IP flags under tracking evidence and location flags under location evidence. I expect that the fix involves widening the scope of the notification function to check for all instances of a given watchlist hash instead of checking only for watchlist hashes in watchlist evidence.

**Comment by lr-brown** [comment]
> After more investigation, this is not a bug but an intentional decision made to categorize IP flags under tracking evidence and location flags under location evidence. I expect that the fix involves widening the scope of the notification function to check for all instances of a given watchlist hash instead of checking only for watchlist hashes in watchlist evidence.

This was in fact the case and the proper fix.

**Comment by SebastianZimmeck** [comment]
@lr-brown, can you give examples of sites for which location and other watchlist notifications work. I have not seen a single notification in my tests.

**Comment by lr-brown** [comment]
I've only been able to get the general keyword of "Hello" to work as that is one of the keyword types that is categorized as a Watchlist evidence type. I am assuming that the above solution will address all instances in which no notification appears. I will confirm after finalizing the solution and testing.

**Comment by SebastianZimmeck** [comment]
> I've only been able to get the general keyword of "Hello" to work as that is one of the keyword types that is categorized as a Watchlist evidence type

OK, good to hear! Though, what is with email address and the other watchlist items?
