### ISSUE TITLE
Move watchlist evidence from tracking to watchlist category

### ISSUE THREAD

**Issue by lr-brown** [privacy-tech-lab/privacy-pioneer#484]
In an effort to provide more clarity for users, we want to move all instances of evidence created from watchlist items to the watchlist category. For example, we currently have it so that instances of IP addresses entered into the watchlist will show up as tracking in evidence. We want to change things like this to a watchlist type.

**Comment by SebastianZimmeck** [comment]
@jjeancharles, can you take care of this? @lr-brown can explain more, also in a call, if you think that would be helpful.

**Comment by JustinCasler** [comment]
I will be taking the lead on this issue.

**Comment by JustinCasler** [comment]
After looking into this issue, I would like to summarize the problem and potential solutions.

- Problem: It's confusing to users that their ip address (which is entered via the watchlist) is not found in the "watchlist" section throughout the extension. 
- Solution 1: Move the ip address evidence from the tracking category to the watchlist category.
  - Potential Issue: This doesn't fix the issue that not all instances of evidence created from watchlist items are displayed in the watchlist category. Street address, zip code, city, and state are all entered via the watchlist but are shown in the location category, not the watchlist.
 - Solution 2: Move all evidence created from watchlist items to the watchlist category.
   - Potential Issue: This is potentially confusing as street address, zip code, city, and state will not be in the location which potentially could be confusing.
- Solution 3: Leave all the evidence in their current categories, but change the "watchlist" category's name because that name is not really accurate as it only has phone numbers, email addresses, and custom keywords. Renaming it to "personal" or something similar would clarify where to find each type of evidence.

I personally would go with solution 3, but I'm open to hearing comments and suggestions.

**Comment by SebastianZimmeck** [comment]
@JustinCasler, I also would go with Solution 3 but with the additional point that IP address is moved from `Tracking` to the new `Personal` category.

So here are the categories:

- Personal
   - General
   - Street address
   - Email address
   - Phone number
   - IP address
- Monetization
   - Advertising
   - Analytics
   - Social
- Location
   - Precise location
   - Coarse location
   - City
   - Region
   - ZIP code
- Tracking
   - Tracking pixel
   - Browser fingerprinting

@JustinCasler, is that what you mean? If not, please correct.  

Our current readme needs to be updated [in that regard](https://coag.gov/app/uploads/2023/03/FINAL-CLEAN-2023.03.15-Official-CPA-Rules.pdf).

**Comment by lr-brown** [comment]
Why wouldn't street address be in location?

**Comment by SebastianZimmeck** [comment]
> Why wouldn't street address be in location?

It is a good point. I would have two reasons, none of which are compelling, though:
- It is a user-entered item, and so just going by formally categorizing all user-entered items under `Personal`, it goes there.
- In the context of web and app tracking location usually means GPS location or coarse cell tower location and not street address (by that reasoning ZIP code, city, and region are also not a good fit for location, but again, the formal view user-entered vs non-user-entered distinction).

**Comment by SebastianZimmeck** [comment]
There might be situations where we may need to use "Personal Watchlist" or something similar, for example, on the settings page. "Settings, Personal, ..." just is not very meaningful.

**Comment by JustinCasler** [comment]
> is that what you mean? If not, please correct.

I was actually proposing 
- Personal
  - General
  - Email address
  - Phone number
- Monetization
  - Advertising
  - Analytics
  - Social
- Location
  - Precise location
  - Coarse location
  - City
  - Region
  - ZIP code
  - Street address
- Tracking
  - Tracking pixel
  - Browser fingerprinting
  - IP address

Which is the same as our current layout just swapping in "Personal" instead of "Watchlist" to make it clear that ip address is in "Tracking" not "Personal" and that street address is in "Location" not "Personal" etc. I thought that this layout would be most clear for users. @SebastianZimmeck, does this make sense? If you prefer your layout we can also move forward with that/discuss on Friday.

**Comment by SebastianZimmeck** [comment]
We can do what you are proposing, @JustinCasler, but then I suggest modifying the Watchlist page layout to make clear what watchlist item goes into which category. This is the main issue that is tripping me up at the moment and that would also happen in your new setup. There are some items that are manually entered under Watchlist (or Personal if renamed) but they  appear under Location (Street address) or Tracking (IP address; not manually entered but under the current Watchlist and then appearing under Tracking). So, my main point is to have a correspondence between what is entered as Watchlist (Personal) item is also later displayed as Watchlist (Personal) item. Now, we can also solve this with a different layout of the Watchlist page. Maybe, we keep calling it Watchlist and then have different categories, e.g.,

- Watchlist
   - Location
      - Add Street address
    - Tracking
       - Add IP address
    ...

**Comment by SebastianZimmeck** [comment]
OK, we go with @JustinCasler's [suggestion](https://github.com/privacy-tech-lab/privacy-pioneer/issues/484#issuecomment-1471117376). The Watchlist terminology in the settings remains, but Watchlist is no longer a category but rather the category is Personal.

The only possible slight modification, and that will be up for @JustinCasler to call on, will be to which extent we surface to which categories the Watchlist items belong. Because as it currently stands the Watchlist does not surface that IP address will be Tracking, Street Address will be Location, etc. Maybe, we do not need to surface that. But maybe when @JustinCasler looks at the UI there is a good way of surfacing it.

**Comment by JustinCasler** [comment]
All changes discussed in this issue have been made and merged into main.
